import { Dimensions } from "react-native";
import moment from "moment";

const { width, height } = Dimensions.get("window");
exports.Theme = {
  primary: "#FF7000",
  lightPrimary: "#ffc69b",
  secondary: "#1c004b",
  grey: "#9c9c9c",
  blue: "#006EBE",
  green: "#09BD09",
  red: "#EE0C0C",
  darkred: "#9F0D0D",
  disabled: "#e6e6e6",
  underline: "#D2D6D8",
  defaultBackground: "#f3f3f3",
  deviceWidth: width,
  CARD_HEIGHT: height / 9,
  CARD_WIDTH: height / 4 - 50,
  margin: 20,
  borderRadius: 12,
  icon: "FontAwesome5",
};

exports.categories = [
  "Social",
  "Professional",
  "Athletic",
  "Learn",
  "Community",
];

exports.eventTags = {
  Social: ["Film", "Food/drink", "Games", "Music", "Networking", "Party"],
  Professional: ["Infosession", "Networking", "Recruiting", "Resume drop"],
  Athletic: ["Recruiting", "Pickup Game", "Watch Party"],
  Learn: ["Infosession", "Lecture", "Workshop"],
  Community: ["Charity", "Fundraiser", "Religion", "Volunteer"],
};

const allTags = new Set();
for (lst of Object.values(exports.eventTags))
  lst.forEach((t) => allTags.add(t));
exports.allEventTags = [...allTags].sort();

moment.updateLocale("en", {
  relativeTime: {
    future: "%s ago",
    past: "%s ago",
    s: "few seconds",
    m: "1m",
    h: "1h",
    d: "1w",
    w: "1w",
    mm: "%dm",
    hh: "%dh",
    dd: "%dd",
    ww: "%dw",
    MM: "%dm",
    yy: "%dy",
  },
});

const gradeLevels = [];
const maxYear = moment().add(4, "y").get("year");
for (let i = maxYear; i >= 2000; i--) gradeLevels.push(i);
exports.gradeLevels = gradeLevels;

exports.majors = [
  "African American Studies",
  "American Studies",
  "Anthropology",
  "Arabic",
  "Architecture",
  "Armenian",
  "Art, History of",
  "Art, Practice of",
  "Asian American and Asian Diaspora Studies",
  "Asian Area Studies I - China",
  "Asian Area Studies II - Japan",
  "Astrophysics",
  "Atmospheric Science",
  "Biochemistry and Molecular Biology",
  "Bioengineering",
  "Bioengineering & Business Administration",
  "Biology + Business Program",
  "Bosnian / Croatian / Serbian",
  "Business Administration",
  "Cell and Developmental Biology",
  "Celtic Studies",
  "Chemical Biology",
  "Chemical Engineering",
  "Chemistry",
  "Chicano/Latino Studies",
  "Chinese",
  "Civil Engineering",
  "Civil Engineering & Business Administration",
  "Classical Civilization",
  "Classical Languages",
  "Classics",
  "Cognitive Science",
  "Comparative Literature",
  "Computer Science",
  "Conservation and Resource Studies",
  "Czech",
  "Dance and Performance Studies",
  "Danish",
  "Data Science",
  "Developmental Studies",
  "Dietetics",
  "Dutch Studies",
  "Earth and Planetary Science",
  "East Asian Languages and Cultures",
  "East Asian Religion, Thought, and Culture",
  "Economics",
  "Ecosystem Management and Forestry",
  "Egyptology",
  "Electrical Engineering and Computer Science",
  "Electrical Engineering and Computer Science & Business Administration",
  "Energy Engineering",
  "Engineering Mathematics and Statistics",
  "Engineering Physics",
  "Engineering Science Programs",
  "English",
  "Environmental Earth Science",
  "Environmental Economics and Policy",
  "Environmental Economics and Policy",
  "Environmental Engineering Science",
  "Environmental Sciences",
  "Ethnic Studies",
  "Film French",
  "Finnish",
  "Forestry",
  "Gender and Women's Studies",
  "Genetics, Genomics, and Development",
  "Genetics and Plant Biology",
  "Geography",
  "Geology",
  "Geophysics",
  "German",
  "Global Management Program",
  "Global Studies",
  "Greek",
  "Hebrew",
  "Hispanic, Languages, Literature, and Bilingualism",
  "History",
  "Hungarian",
  "Immunology and Pathogenesis",
  "Industrial Engineering and Operations Research",
  "Industrial Engineering and Operations Research & Business Administration",
  "Integrative Biology",
  "Interdisciplinary Studies",
  "Italian Studies",
  "Japanese",
  "Landscape Architecture",
  "Languages, Literature, and Cultures in the Portuguese - Speaking World",
  "Languages, Literature, and Cultures in the Spanish - Speaking World",
  "Latin",
  "Latin American Languages, Literature, and Cultures",
  "Latin American Studies",
  "Legal Studies",
  "Linguistics",
  "Management, Entrepreneurship, and Technology (M.E.T.)",
  "Marine Science",
  "Materials Science and Engineering",
  "Materials Science and Engineering & Business Administration",
  "Mathematics",
  "Mathematics, Applied",
  "Mechanical Engineering",
  "Mechanical Engineering & Business Administration",
  "Media Studies",
  "Microbial Biology",
  "Middle Eastern Studies",
  "Molecular and Cell Biology",
  "Molecular Environmental Biology",
  "Molecular Toxicology",
  "Music",
  "Native American Studies",
  "Natural Resource Management",
  "Near Eastern Civilizations",
  "Near Eastern Languages and Literature",
  "Neurobiology",
  "Nowegian",
  "Nuclear Engineering",
  "Nutritional Sciences",
  "Old Norse",
  "Operations Research and Management Sciences",
  "Peace and Conflict Studies",
  "Persian",
  "Philosophy",
  "Physics",
  "Physiology and Metabolism",
  "Planetary Science",
  "Polish",
  "Political Economy",
  "Political Science",
  "Psychology",
  "Public Health",
  "Rhetoric",
  "Russian",
  "Scandinavian",
  "Slavic",
  "Social Welfare",
  "Society and Environment",
  "Sociology",
  "South and Southeast Asian Studies",
  "Spanish and Portuguese",
  "Statistics",
  "Sustainable Environmental Design",
  "Swedish",
  "Theater, Dance, and Performance Studies",
  "Theater and Performance Studies",
  "Undeclared",
  "Urban Studies",
];
